val y = Node(9,Node(7,Leaf('c',3),Leaf('b',4)),Leaf('c',2))
val z = Node(9,Node(7,Leaf('c',3),Leaf('b',4)),Leaf('c',2))
val a = Node(4,Node(2,Leaf('c',1),Leaf('b',1)),Leaf('y',2))
val tree1 = Huffman.combine(y,z)
val tree2 = Huffman.combine(a,a)
println(tree1)
println("")
println(tree2)
println("")